### ISSUE TITLE
garage issue 

### ISSUE THREAD

**Issue by cummins24v2** [Brazzers-Development/brazzers-fakeplates#1]
![image](https://user-images.githubusercontent.com/97122395/198910992-ec017981-7d32-4688-a5e2-e5366ce49fab.png)
![image](https://user-images.githubusercontent.com/97122395/198911004-14079f40-cdd4-4c51-8b3c-873d4a4a501a.png)
when i put a car in the garage with a fake plate it shows that in there on my phone but it not actually i put the code that was  in the read me

**Comment by MannyOnBrazzers** [comment]
Can you do me a favor, can you screenshot the table of the vehicle in player_vehicles.

**Comment by MannyOnBrazzers** [comment]
No response, closing issue for now.
